version: "1.0"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/bun-hono-backend
      - JWT_SECRET=your-secret-key
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASS=your-app-password
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=bun-hono-backend
    ports:
      - "5432:5432"
    volumes:
      # - postgres-data:/var/lib/postgresql/data
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
